version: "3.8"
services:
  db:
    image: ngmondial
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@hs-pforzheim.de
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
