slice_name: Birth Years of Customers
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 25__table
  viz_type: big_number
  x_axis: BirthDate
  time_grain_sqla: P1Y
  metric: count
  adhoc_filters:
  - clause: WHERE
    subject: BirthDate
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  show_trend_line: true
  start_y_axis_at_zero: true
  color_picker:
    r: 0
    g: 122
    b: 135
    a: 1
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: None
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":25,"type":"table"},"force":false,"queries":[{"filters":[{"col":"BirthDate","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1Y","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1Y","columnType":"BASE_AXIS","sqlExpression":"BirthDate","label":"BirthDate","expressionType":"SQL"}],"metrics":["count"],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"pivot","options":{"index":["BirthDate"],"columns":[],"aggregates":{"count":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"25__table","viz_type":"big_number","x_axis":"BirthDate","time_grain_sqla":"P1Y","metric":"count","adhoc_filters":[{"clause":"WHERE","subject":"BirthDate","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"show_trend_line":true,"start_y_axis_at_zero":true,"color_picker":{"r":0,"g":122,"b":135,"a":1},"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","rolling_type":"None","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 4f1b2f66-3704-4121-abf7-26bb3c3285e4
version: 1.0.0
dataset_uuid: a65b9227-dbd6-4519-b1a1-6bb0be974a36
